[package]
name = "graph-builder"
version = "0.1.0"
authors = ["Alex Crawford <crawford@redhat.com>"]

[dependencies]
actix = "^0.7.6"
actix-web = "^0.7.8"
cincinnati = { path = "../cincinnati" }
commons = { path = "../commons" }
dkregistry = { git = "https://github.com/camallo/dkregistry-rs.git", rev = "a10c1aba444ce5c07e113c81160eb67c9711e327" }
env_logger = "^0.6.0"
failure = "^0.1.1"
flate2 = "^1.0.1"
futures = "0.1"
itertools = "^0.7.8"
lazy_static = "^1.2.0"
log = "^0.4.3"
prometheus = "^0.4.2"
quay = { path = "../quay" }
regex = "^1.1.0"
reqwest = "^0.9.0"
semver = { version = "^0.9.0", features = [ "serde" ] }
serde = "^1.0.70"
serde_derive = "^1.0.70"
serde_json = "^1.0.22"
structopt = "^0.2.10"
tar = "^0.4.16"
tokio = "0.1"
toml = "^0.4.10"
url = "^1.7.2"

[features]
test-net = []
test-net-private = []
